services:

    openproduct:
        image: maykinmedia/open-product:1.1.0
        container_name: openproduct-test
        platform: linux/amd64
        ports:
            - "9070:8000"
        environment: &open-product-env
            - DJANGO_SETTINGS_MODULE=openproduct.conf.docker
            - SECRET_KEY=${SECRET_KEY:-django-insecure-@4wj9(+*bu7*v&%on7+e_8!d1ckl%r=6+sz#d2!pw^@lb0+=}
            - DB_NAME=openproduct
            - DB_USER=openproduct
            - DB_PASSWORD=openproduct
            - DB_HOST=openproduct-database
            - PORT=5432
            - CACHE_DEFAULT=redis://openproduct-redis:6379/0
            - CELERY_BROKER_URL=redis://openproduct-redis:6379/1
            - CELERY_RESULT_BACKEND=redis://openproduct-redis:6379/1
            # Only allow all hosts for development/testing purposes!
            - ALLOWED_HOSTS=*
            - DISABLE_2FA=true
        depends_on:
            - openproduct-database
            - openproduct-redis
        volumes:
            - ./imports/openproduct/init/UPL-actueel.csv:/app/UPL-actueel.csv
            - ./imports/openproduct/init:/app/init
        command: sh /app/init/init.sh

    openproduct-celery:
        image: maykinmedia/open-product:1.0.0
        container_name: openproduct-celery-test
        platform: linux/amd64
        environment: *open-product-env
        command: /celery_worker.sh

    openproduct-database:
        image: postgres:17
        container_name: openproduct-database-test
        ports:
            - "54320:5432"
        environment:
            - POSTGRES_USER=${DB_USER:-openproduct}
            - POSTGRES_PASSWORD=${DB_PASSWORD:-openproduct}
            - POSTGRES_DB=openproduct
        volumes:
            - ./imports/openproduct/database:/docker-entrypoint-initdb.d/

    openproduct-redis:
        image: redis:6.2.6
        container_name: openproduct-redis-test
