/*
 * Copyright 2015-2023 Ritense BV, the Netherlands.
 *
 * Licensed under EUPL, Version 1.2 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package nl.nlportal.payment.qrlink.api

import nl.nlportal.payment.qrlink.domain.QRLinkPaymentCodeFileType
import nl.nlportal.payment.qrlink.domain.QRLinkPaymentResponse
import nl.nlportal.payment.qrlink.service.QRLinkPaymentService
import org.apache.commons.io.FileUtils
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController
import org.springframework.web.server.ResponseStatusException

@RestController
@RequestMapping(path = ["/api/public/payment/qrlink"])
@ConditionalOnProperty(prefix = "nl-portal.config.payment", name = ["qrlink.enabled", "direct.enabled"], havingValue = "true")
class QRLinkPaymentController(
    private val qrLinkPaymentService: QRLinkPaymentService
) {
    /**
     *  Get a redirect url generated by Wordline
     * @param identifier: the identifier as specified in the configuration with PSP ID and other payment properties
     * @param amount: amount for the payment, should be in euro cents
     * @param orderid: the payment identifier
     * @param reference: a reference to the payment
     * @param language: the language of the payment page, like nl_NL or en_US. Is optional
     * @param returnurl: the return url after payment. Is optional
     * @return the redirectUrl to Ogone/Wordline payment page
     */
    @GetMapping("/pay")
    suspend fun doPayment(
        @RequestParam("identifier") identifier: String,
        @RequestParam("amount") amount: Double,
        @RequestParam("orderid") orderid: String,
        @RequestParam("reference") reference: String,
        @RequestParam("language", required = false) language: String? = null,
        @RequestParam("returnurl", required = false) returnUrl: String? = null,
        @RequestParam("hash", required = false) hash: String? = null,
    ): ResponseEntity<Any> {
        try {
            return ResponseEntity.ok(
                qrLinkPaymentService.doBetaling(
                    identifier = identifier,
                    amount = amount,
                    reference = reference,
                    language = language,
                    returnUrl = returnUrl,
                    orderid = orderid,
                    hash = hash,
                ),
            )
        } catch (e: ResponseStatusException) {
            return ResponseEntity.status(e.statusCode).body(e.message)
        }
    }

    /**
     *  Get the status of the payment
     * @param identifier: the identifier as specified in the configuration with PSP ID and other payment properties
     * @param hostedCheckoutId: id of the payment
     * @return the payment status
     */
    @GetMapping("/status")
    suspend fun getStatus(
        @RequestParam("identifier") identifier: String,
        @RequestParam("hostedCheckoutId") hostedCheckoutId: String,
    ): ResponseEntity<Any> {
        try {
            return ResponseEntity.ok(
                qrLinkPaymentService.getStatus(
                    identifier = identifier,
                    hostedCheckoutId = hostedCheckoutId,
                ),
            )
        } catch (e: ResponseStatusException) {
            return ResponseEntity.status(e.statusCode).body(e.message)
        }
    }

    /**
     *  Generate a betaal QR Code, but only if identifier is configured
     *  is protected by an x-api-key header, which is a SHA512 hash of the identifier
     * @param identifier: the identifier as specified in the configuration with PSP ID and other payment properties
     * @param amount: amount for the payment, should be in euro cents
     * @param orderid: the payment identifier
     * @param reference: a reference to the payment
     * @param height: the height of the QR code in pixels. Is optional
     * @param width: the width of the QR code in pixels. Is optional
     * @param returnurl: the return url after payment. Is optional
     * @param filetype: the qrcode file type. Supported file types are PNG, GIF, JPG. Is optional, default is PNG.
     * @param subject: a subject which is displayed on the landing page of the payment. Is Optional
     * @param margin: the margin of around the qrcode. Is Optional
     * @return a base64 encode qrcode
     */
    @GetMapping("/generate/qrcode")
    fun qrcode(
        @RequestParam("identifier") identifier: String,
        @RequestParam("amount") amount: Int,
        @RequestParam("orderid") orderid: String,
        @RequestParam("reference") reference: String,
        @RequestParam("height", required = false) height: Int? = null,
        @RequestParam("width", required = false) width: Int? = null,
        @RequestParam("returnurl", required = false) returnurl: String? = null,
        @RequestParam("filetype", required = false) filetype: QRLinkPaymentCodeFileType? = null,
        @RequestParam("subject", required = false) subject: String? = null,
        @RequestParam("margin", required = false) margin: Int? = null,
    ): ResponseEntity<Any> =
        ResponseEntity.ok(
            qrLinkPaymentService.generateQrCode(
                identifier = identifier,
                amountInCents = amount,
                reference = reference,
                height = height,
                width = width,
                orderid = orderid,
                returnUrl = returnurl,
                qrCodeFileType = filetype,
                subject = subject,
                margin = margin,
            ),
        )

    /**
     *  Generate a betaal QR Code file, but only if identifier is configured
     *  is protected by an x-api-key header, which is a SHA512 hash of the identifier
     * @param identifier: the identifier as specified in the configuration with PSP ID and other payment properties
     * @param amount: amount for the payment, should be in euro cents
     * @param orderid: the payment identifier
     * @param reference: a reference to the payment
     * @param height: the height of the QR code in pixels. Is optional
     * @param width: the width of the QR code in pixels. Is optional
     * @param returnurl: the return url after payment. Is optional
     * @param filetype: the qrcode file type. Supported file types are PNG, GIF, JPG. Is optional, default is PNG.
     * @param subject: a subject which is displayed on the landing page of the payment. Is Optional
     * @param margin: the margin of around the qrcode. Is Optional
     * @return a file as ByteArray
     */
    @GetMapping("/generate/qrcode/download")
    fun qrcodeStream(
        @RequestParam("identifier") identifier: String,
        @RequestParam("amount") amount: Int,
        @RequestParam("orderid") orderid: String,
        @RequestParam("reference") reference: String,
        @RequestParam("height", required = false) height: Int? = null,
        @RequestParam("width", required = false) width: Int? = null,
        @RequestParam("returnurl", required = false) returnurl: String? = null,
        @RequestParam("filetype", required = false) filetype: QRLinkPaymentCodeFileType? = null,
        @RequestParam("subject", required = false) subject: String? = null,
        @RequestParam("margin", required = false) margin: Int? = null,
    ): ResponseEntity<ByteArray> =
        ResponseEntity
            .ok()
            .contentType(MediaType.APPLICATION_OCTET_STREAM)
            .body(
                FileUtils.readFileToByteArray(
                    qrLinkPaymentService.generateQrCodeFile(
                        identifier = identifier,
                        amountInCents = amount,
                        reference = reference,
                        height = height,
                        width = width,
                        returnUrl = returnurl,
                        orderid = orderid,
                        qrCodeFileType = filetype,
                        subject = subject,
                        margin = margin,
                    ),
                ),
            )

    /**
     *  Generate a betaal link, but only if identifier is configured
     *  is protected by an x-api-key header, which is a SHA512 hash of the identifier
     * @param identifier: the identifier as specified in the configuration with PSP ID and other payment properties
     * @param amount: amount for the payment, should be in euro cents
     * @param orderid: the payment identifier
     * @param reference: a reference to the payment
     * @param returnurl: the return url after payment. Is optional
     * @param subject: a subject which is displayed on the landing page of the payment. Is Optional
     * @return a payment link
     */
    @GetMapping("/generate/link")
    fun link(
        @RequestParam("identifier") identifier: String,
        @RequestParam("amount") amount: Int,
        @RequestParam("orderid") orderid: String,
        @RequestParam("reference") reference: String,
        @RequestParam("returnurl", required = false) returnurl: String? = null,
        @RequestParam("subject", required = false) subject: String? = null,
    ): ResponseEntity<QRLinkPaymentResponse> =
        ResponseEntity.ok(
            QRLinkPaymentResponse(
                link =
                    qrLinkPaymentService.generateLink(
                        identifier = identifier,
                        amountInCents = amount,
                        orderid = orderid,
                        reference = reference,
                        returnUrl = returnurl,
                        subject = subject,
                    ),
            ),
        )
}
