server:
    port: 8081

spring:
    application:
        name: nl-portal-backend-libraries
    liquibase:
        enabled: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        hostname: ${DATABASE_HOSTNAME:localhost}
        database-name: ${DATABASE_NAME:valtimo-portal-db}
        port: ${DATABASE_PORT:5432}
        url: jdbc:postgresql://${spring.datasource.hostname}:${spring.datasource.port}/${spring.datasource.database-name}
        name: valtimo-portal-db
        username: ${DATABASE_USERNAME:postgres}
        password: ${DATABASE_PASSWORD:test}
        hikari:
            auto-commit: false
            poolName: "valtimo-portal-pool"
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQL10Dialect
        database: postgresql
        show_sql: true
        open-in-view: false
        properties:
            hibernate:
                hbm2ddl.auto: none
                generate_statistics: false
                naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
                cache:
                    use_second_level_cache: false
                    use_query_cache: false
                    region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
                format_sql: true
                jdbc:
                    time_zone: UTC
                connection:
                    provider_disables_autocommit: true
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8092/auth/realms/valtimo

graphql:
    introspection:
        enabled: true
    packages:
        - "com.ritense.portal"
logging:
    level:
        org:
            springframework:
                amqp: DEBUG

valtimo:
    cors:
        -   path: "/**"
            config:
                allowedHeaders: "*"
                allowedOrigins: "*"
                allowedMethods: "*"
