query {
    getOpenProductActies(
        pageNumber: 1,
        pageSize: 20
     ){
        number
         size
         totalElements
         numberOfElements
         content {
            uuid,
            url,
            naam
        }
    }
}
