query {
    getOpenProductenByThema(
        themaId: "41f71c2e-9e0c-4a1b-8d39-709669b256c2"
     ){
        uuid,
        url,
        naam,
        startDatum,
        gepubliceerd,
        aanmaakDatum,
        producttype {
            code,
            uniformeProductNaam,
            toegestaneStatussen,
        }
        prijs,
        gepubliceerd,
        status,
        documenten {
            url
        },
        frequentie,
        verbruiksobject,
        dataobject
    }
}
