query {
    getOpenProductHoofdThemas {
          uuid,
          naam,
          beschrijving,
          gepubliceerd,
          hoofdThema,
          producttypen {
              uuid,
              code,
              uniformeProductNaam
          },
          aanmaakDatum,
          updateDatum
      }
}
