query {
    getOpenProducten(
        pageNumber: 1,
        pageSize: 20,
        status: "actief",
     ){
        number
         size
         totalElements
         numberOfElements
         content {
            uuid,
            url,
            startDatum,
            gepubliceerd,
            aanmaakDatum,
            producttype {
                code,
                uniformeProductNaam,
                toegestaneStatussen,
            }
            prijs,
            gepubliceerd,
            status,
            documenten {
                uuid,
                documentapi,
                identificatie,
                creatiedatum,
                titel,
                formaat,
                bestandsnaam,
                bestandsomvang
            },
            frequentie,
            verbruiksobject,
            dataobject
        }
    }
}
