query {
    getThemas {
        uuid,
        naam,
        beschrijving,
        gepubliceerd,
        producttypen {
            uuid,
            code,
            uniformeProductNaam
        },
        aanmaakDatum,
        updateDatum
    }
}
