query {
    getThemas(
        pageNumber: 1,
        pageSize: 20
     ){
        number
         size
         totalElements
         numberOfElements
         content {
            uuid,
            naam,
            beschrijving,
            gepubliceerd,
            producttypen {
                uuid,
                code,
                uniformeProductNaam
            },
            aanmaakDatum,
            updateDatum
        }
    }
}
