services:

  # openklant 2
  openklant-2:
      image: maykinmedia/open-klant:2.1.0
      container_name: openklant-2-test
      ports:
          - "9007:8000"
      depends_on:
          - openklant-2-db
          - redis
      environment:
          - DJANGO_SETTINGS_MODULE=openklant.conf.docker
          - IS_HTTPS=no
          - DB_NAME=openklant
          - DB_USER=openklant
          - DB_PASSWORD=openklant
          - DB_HOST=openklant-2-db
          - ALLOWED_HOSTS=*
          - CACHE_DEFAULT=redis-test:6379/0
          - CACHE_AXES=redis-test:6379/0
          - SUBPATH=${SUBPATH:-/}
          - SECRET_KEY=${SECRET_KEY:-django-insecure-f8s@b*ds4t84-q_2#c0j0506@!l2q6r5_pq5e!vm^_9c*#^66b}
          - CELERY_BROKER_URL=redis://redis-test:6379/0
          - CELERY_RESULT_BACKEND=redis://redis-test:6379/0
          - DISABLE_2FA=true
      volumes:
          - ./imports/openklant-2/init:/app/init
      command: sh /app/init/init.sh

  openklant-2-db:
      image: postgres:15
      container_name: openklant-2-db-test
      environment:
          - POSTGRES_USER=openklant
          - POSTGRES_PASSWORD=openklant
          - POSTGRES_DB=openklant
      volumes:
          - ./imports/openklant-2/database:/docker-entrypoint-initdb.d/

  redis:
      image: redis:6.2.6
      container_name: redis-test