spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/nl-portal
        username: nlportal
        password: password
        name: nl-portal-database

logging:
    level:
        reactor.netty.http.client.HttpClient: DEBUG