server:
    port: 8090

spring:
    datasource:
        url: jdbc:postgresql://localhost:54321/nl-portal
        username: nlportal
        password: password
        name: nl-portal-database

logging:
    level:
        reactor.netty.http.client.HttpClient: DEBUG