/*
 * Copyright 2024 Ritense BV, the Netherlands.
 *
 * Licensed under EUPL, Version 1.2 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package nl.nlportal.openklant.client.domain

import com.fasterxml.jackson.annotation.JsonValue

data class OpenKlant2ForeignKey(
    val url: String,
    val uuid: String,
)

data class OpenKlant2Identificator(
    val objectId: String = "",
    val codeObjecttype: String = "",
    val codeRegister: String = "",
    val codeSoortObjectId: String = "",
) {
    init {
        require(objectId.length <= 200) {
            "ObjectID can't be longer than 200 characters"
        }
        require(codeObjecttype.length <= 200) {
            "ObjectID can't be longer than 200 characters"
        }
        require(codeRegister.length <= 200) {
            "ObjectID can't be longer than 200 characters"
        }
        require(codeSoortObjectId.length <= 200) {
            "ObjectID can't be longer than 200 characters"
        }
    }
}

data class OpenKlant2Adres(
    val adresregel1: String? = null,
    val adresregel2: String? = null,
    val adresregel3: String? = null,
    val land: Landcode? = null,
    val nummeraanduidingId: String? = null,
) {
    init {
        require(nummeraanduidingId == null || nummeraanduidingId.length <= 255) {
            "Adresregel1 can't be more than 255 characters long."
        }
        require(adresregel1 == null || adresregel1.length <= 80) {
            "Adresregel1 can't be more than 255 characters long."
        }
        require(adresregel2 == null || adresregel2.length <= 80) {
            "Adresregel1 can't be more than 255 characters long."
        }
        require(adresregel3 == null || adresregel3.length <= 80) {
            "Adresregel1 can't be more than 255 characters long."
        }
    }
}

enum class Landcode(
    @JsonValue val landcode: String,
    val landnaam: String,
) {
    CANADA("5001", "Canada"),
    FRANKRIJK("5002", "Frankrijk"),
    ZWITSERLAND("5003", "Zwitserland"),
    RHODESIE("5004", "Rhodesië"),
    MALAWI("5005", "Malawi"),
    CUBA("5006", "Cuba"),
    SURINAME("5007", "Suriname"),
    TUNESIE("5008", "Tunesië"),
    OOSTENRIJK("5009", "Oostenrijk"),
    BELGIE("5010", "België"),
    BOTSWANA("5011", "Botswana"),
    IRAN("5012", "Iran"),
    NIEUWZEELAND("5013", "Nieuw-Zeeland"),
    ZUIDAFRIKA("5014", "Zuid-Afrika"),
    DENEMARKEN("5015", "Denemarken"),
    NOORDJEMEN("5016", "Noord-Jemen"),
    HONGARIJE("5017", "Hongarije"),
    SAOEDIARABIE("5018", "Saoedi-Arabië"),
    LIBERIA("5019", "Liberia"),
    ETHIOPIE("5020", "Ethiopië"),
    CHILI("5021", "Chili"),
    MAROKKO("5022", "Marokko"),
    TOGO("5023", "Togo"),
    GHANA("5024", "Ghana"),
    LAOS("5025", "Laos"),
    ANGOLA("5026", "Angola"),
    FILIPIJNEN("5027", "Filipijnen"),
    ZAMBIA("5028", "Zambia"),
    MALI("5029", "Mali"),
    IVOORKUST("5030", "Ivoorkust"),
    BURMA("5031", "Burma"),
    MONACO("5032", "Monaco"),
    COLOMBIA("5033", "Colombia"),
    ALBANIE("5034", "Albanië"),
    KAMEROEN("5035", "Kameroen"),
    ZUIDVIETNAM("5036", "Zuid-Vietnam"),
    SINGAPORE("5037", "Singapore"),
    PARAGUAY("5038", "Paraguay"),
    ZWEDEN("5039", "Zweden"),
    CYPRUS("5040", "Cyprus"),
    AUSTRALISCH_NIEUWGUINEA("5041", "Australisch Nieuw-Guinea"),
    BRUNEI("5042", "Brunei"),
    IRAK("5043", "Irak"),
    MAURITIUS("5044", "Mauritius"),
    VATICAANSTAD("5045", "Vaticaanstad"),
    KASHMIR("5046", "Kashmir"),
    MYANMAR("5047", "Myanmar"),
    JEMEN("5048", "Jemen"),
    SLOVENIE("5049", "Slovenië"),
    ZAIRE("5050", "Zaïre"),
    KROATIE("5051", "Kroatië"),
    TAIWAN("5052", "Taiwan"),
    RUSLAND("5053", "Rusland"),
    ARMENIE("5054", "Armenië"),
    ASCENSION("5055", "Ascension"),
    AZOREN("5056", "Azoren"),
    BAHREIN("5057", "Bahrein"),
    BHUTAN("5058", "Bhutan"),
    BRITSE_ANTILLEN("5059", "Britse Antillen"),
    COMOREN("5060", "Comoren"),
    FALKLANDEILANDEN("5061", "Falklandeilanden"),
    FRANSGUYANA("5062", "Frans-Guyana"),
    FRANSSOMALILAND("5063", "Frans-Somaliland"),
    GILBERT_EN_ELLICEEILANDEN("5064", "Gilbert- en Ellice-eilanden"),
    GROENLAND("5065", "Groenland"),
    GUADELOUPE("5066", "Guadeloupe"),
    KAAPVERDISCHE_EILANDEN("5067", "Kaapverdische Eilanden"),
    MACAU("5068", "Macau"),
    MARTINIQUE("5069", "Martinique"),
    MOZAMBIQUE("5070", "Mozambique"),
    PITCAIRNEILANDEN("5071", "Pitcairneilanden"),
    GUINEEBISSAU("5072", "Guinee-Bissau"),
    REUNION("5073", "Réunion"),
    SAINT_PIERRE_EN_MIQUELON("5074", "Saint Pierre en Miquelon"),
    SEYCHELLEN_EN_AMIRANTEN("5075", "Seychellen en Amiranten"),
    TONGA("5076", "Tonga"),
    WALLIS_EN_FUTUNA("5077", "Wallis en Futuna"),
    ZUIDWESTAFRIKA("5078", "Zuidwest-Afrika"),
    FRANSINDIE("5079", "Frans-Indië"),
    JOHNSTON("5080", "Johnston"),
    KEDAH("5081", "Kedah"),
    KELANTAN("5082", "Kelantan"),
    MALAKKA("5083", "Malakka"),
    MAYOTTE("5084", "Mayotte"),
    NEGRI_SEMBILAN("5085", "Negri Sembilan"),
    PAHANG("5086", "Pahang"),
    PERAK("5087", "Perak"),
    PERLIS("5088", "Perlis"),
    PORTUGEESINDIE("5089", "Portugees-Indië"),
    SELANGOR("5090", "Selangor"),
    SIKKIM("5091", "Sikkim"),
    SAINT_VINCENT_EN_DE_GRENADINES("5092", "Saint Vincent en de Grenadines"),
    SPITSBERGEN("5093", "Spitsbergen"),
    TRENGGANU("5094", "Trengganu"),
    ARUBA("5095", "Aruba"),
    BURKINA_FASO("5096", "Burkina Faso"),
    AZERBEIDZJAN("5097", "Azerbeidzjan"),
    BELARUS("5098", "Belarus"),
    KAZACHSTAN("5099", "Kazachstan"),
    MACEDONIE("5100", "Macedonië"),
    TIMOR_LESTE("5101", "Timor Leste"),
    SERVIE_EN_MONTENEGRO("5102", "Servië en Montenegro"),
    SERVIE("5103", "Servië"),
    MONTENEGRO("5104", "Montenegro"),
    KOSOVO("5105", "Kosovo"),
    BONAIRE("5106", "Bonaire"),
    CURACAO("5107", "Curaçao"),
    SABA("5108", "Saba"),
    SINT_EUSTATIUS("5109", "Sint Eustatius"),
    SINT_MAARTEN("5110", "Sint Maarten"),
    ZUIDSOEDAN("5111", "Zuid-Soedan"),
    GAZASTROOK_EN_WESTELIJKE_JORDAANOEVER("5112", "Gazastrook en Westelijke Jordaanoever"),
    REPUBLIEK_NOORDMACEDONIE("5113", "Republiek Noord-Macedonië"),
    MOLDAVIE("6000", "Moldavië"),
    BURUNDI("6001", "Burundi"),
    FINLAND("6002", "Finland"),
    GRIEKENLAND("6003", "Griekenland"),
    GUATEMALA("6004", "Guatemala"),
    NIGERIA("6005", "Nigeria"),
    LIBIE("6006", "Libië"),
    IERLAND("6007", "Ierland"),
    BRAZILIE("6008", "Brazilië"),
    RWANDA("6009", "Rwanda"),
    VENEZUELA("6010", "Venezuela"),
    IJSLAND("6011", "IJsland"),
    LIECHTENSTEIN("6012", "Liechtenstein"),
    SOMALIE("6013", "Somalië"),
    VERENIGDE_STATEN_VAN_AMERIKA("6014", "Verenigde Staten van Amerika"),
    BOLIVIA("6015", "Bolivia"),
    AUSTRALIE("6016", "Australië"),
    JAMAICA("6017", "Jamaica"),
    LUXEMBURG("6018", "Luxemburg"),
    TSJAAD("6019", "Tsjaad"),
    MAURITANIE("6020", "Mauritanië"),
    KIRGIZIE("6021", "Kirgizië"),
    CHINA("6022", "China"),
    AFGHANISTAN("6023", "Afghanistan"),
    INDONESIE("6024", "Indonesië"),
    GUYANA("6025", "Guyana"),
    NOORDVIETNAM("6026", "Noord-Vietnam"),
    NOORWEGEN("6027", "Noorwegen"),
    SAN_MARINO("6028", "San Marino"),
    DUITSLAND("6029", "Duitsland"),
    NEDERLAND("6030", "Nederland"),
    CAMBODJA("6031", "Cambodja"),
    FIJI("6032", "Fiji"),
    BAHAMAS("6033", "Bahama's"),
    ISRAEL("6034", "Israël"),
    NEPAL("6035", "Nepal"),
    ZUIDKOREA("6036", "Zuid-Korea"),
    SPANJE("6037", "Spanje"),
    OEKRAINE("6038", "Oekraïne"),
    VERENIGD_KONINKRIJK("6039", "Verenigd Koninkrijk"),
    NIGER("6040", "Niger"),
    HAITI("6041", "Haïti"),
    JORDANIE("6042", "Jordanië"),
    TURKIJE("6043", "Turkije"),
    TRINIDAD_EN_TOBAGO("6044", "Trinidad en Tobago"),
    JOEGOSLAVIE("6045", "Joegoslavië"),
    OPPERVOLTA("6046", "Opper-Volta"),
    ALGERIJE("6047", "Algerije"),
    GABON("6048", "Gabon"),
    NOORDKOREA("6049", "Noord-Korea"),
    OEZBEKISTAN("6050", "Oezbekistan"),
    SIERRA_LEONE("6051", "Sierra Leone"),
    BRITSHONDURAS("6052", "Brits-Honduras"),
    CANARISCHE_EILANDEN("6053", "Canarische Eilanden"),
    FRANSPOLYNESIE("6054", "Frans-Polynesië"),
    GIBRALTAR("6055", "Gibraltar"),
    PORTUGEESTIMOR("6056", "Portugees-Timor"),
    TADZJIKISTAN("6057", "Tadzjikistan"),
    BRITSE_SALOMONSEILANDEN("6058", "Britse Salomonseilanden"),
    SAO_TOME_EN_PRINCIPE("6059", "São Tomé en Principe"),
    SINTHELENA("6060", "Sint-Helena"),
    TRISTAN_DA_CUNHA("6061", "Tristan Da Cunha"),
    WESTSAMOA("6062", "West-Samoa"),
    TURKMENISTAN("6063", "Turkmenistan"),
    GEORGIE("6064", "Georgië"),
    BOSNIEHERZEGOVINA("6065", "Bosnië-Herzegovina"),
    TSJECHIE("6066", "Tsjechië"),
    SLOWAKIJE("6067", "Slowakije"),
    FEDERALE_REPUBLIEK_JOEGOSLAVIE("6068", "Federale Republiek Joegoslavië"),
    DEMOCRATISCHE_REPUBLIEK_CONGO("6069", "Democratische Republiek Congo"),
    UGANDA("7001", "Uganda"),
    KENYA("7002", "Kenya"),
    MALTA("7003", "Malta"),
    BARBADOS("7004", "Barbados"),
    ANDORRA("7005", "Andorra"),
    MEXICO("7006", "Mexico"),
    COSTA_RICA("7007", "Costa Rica"),
    GAMBIA("7008", "Gambia"),
    SYRIE("7009", "Syrië"),
    NEDERLANDSE_ANTILLEN("7011", "Nederlandse Antillen"),
    ZUIDJEMEN("7012", "Zuid-Jemen"),
    EGYPTE("7014", "Egypte"),
    ARGENTINIE("7015", "Argentinië"),
    LESOTHO("7016", "Lesotho"),
    HONDURAS("7017", "Honduras"),
    NICARAGUA("7018", "Nicaragua"),
    PAKISTAN("7020", "Pakistan"),
    SENEGAL("7021", "Senegal"),
    DAHOMEY("7023", "Dahomey"),
    BULGARIJE("7024", "Bulgarije"),
    MALEISIE("7026", "Maleisië"),
    DOMINICAANSE_REPUBLIEK("7027", "Dominicaanse Republiek"),
    POLEN("7028", "Polen"),
    RUSLAND_OUD("7029", "Rusland (oud)"),
    BRITSE_MAAGDENEILANDEN("7030", "Britse Maagdeneilanden"),
    TANZANIA("7031", "Tanzania"),
    EL_SALVADOR("7032", "El Salvador"),
    SRI_LANKA("7033", "Sri Lanka"),
    SOEDAN("7034", "Soedan"),
    JAPAN("7035", "Japan"),
    HONGKONG("7036", "Hongkong"),
    PANAMA("7037", "Panama"),
    URUGUAY("7038", "Uruguay"),
    ECUADOR("7039", "Ecuador"),
    GUINEE("7040", "Guinee"),
    MALDIVEN("7041", "Maldiven"),
    THAILAND("7042", "Thailand"),
    LIBANON("7043", "Libanon"),
    ITALIE("7044", "Italië"),
    KOEWEIT("7045", "Koeweit"),
    INDIA("7046", "India"),
    ROEMENIE("7047", "Roemenië"),
    TSJECHOSLOWAKIJE("7048", "Tsjecho-Slowakije"),
    PERU("7049", "Peru"),
    PORTUGAL("7050", "Portugal"),
    OMAN("7051", "Oman"),
    MONGOLIE("7052", "Mongolië"),
    SAMOA("7053", "Samoa"),
    VERENIGDE_ARABISCHE_EMIRATEN("7054", "Verenigde Arabische Emiraten"),
    TIBET("7055", "Tibet"),
    NAURU("7057", "Nauru"),
    NEDERLANDS_NIEUWGUINEA("7058", "Nederlands Nieuw-Guinea"),
    TANGANYIKA("7059", "Tanganyika"),
    PALESTINA("7060", "Palestina"),
    BRITS_WESTINDIE("7062", "Brits West-Indië"),
    PORTUGEESAFRIKA("7063", "Portugees-Afrika"),
    LETLAND("7064", "Letland"),
    ESTLAND("7065", "Estland"),
    LITOUWEN("7066", "Litouwen"),
    BRITSAFRIKA("7067", "Brits-Afrika"),
    BELGISCHCONGO("7068", "Belgisch-Congo"),
    BRITSINDIE("7070", "Brits-Indië"),
    NOORDRHODESIE("7071", "Noord-Rhodesië"),
    ZUIDRHODESIE("7072", "Zuid-Rhodesië"),
    SAARLAND("7073", "Saarland"),
    FRANS_INDOCHINA("7074", "Frans Indochina"),
    BRITS_WESTBORNEO("7075", "Brits West-Borneo"),
    GOUDKUST("7076", "Goudkust"),
    RAS_ALKHAIMAH("7077", "Ras al-Khaimah"),
    FRANSCONGO("7079", "Frans-Congo"),
    SIAM("7080", "Siam"),
    BRITS_OOSTAFRIKA("7082", "Brits Oost-Afrika"),
    BRITS_NOORDBORNEO("7083", "Brits Noord-Borneo"),
    BANGLADESH("7084", "Bangladesh"),
    DUITSE_DEMOCRATISCHE_REPUBLIEK("7085", "Duitse Democratische Republiek"),
    MADEIRAEILANDEN("7087", "Madeira-eilanden"),
    AMERIKAANSE_MAAGDENEILANDEN("7088", "Amerikaanse Maagdeneilanden"),
    AUSTRALISCHE_SALOMONSEILANDEN("7089", "Australische Salomonseilanden"),
    SPAANSE_SAHARA("7091", "Spaanse Sahara"),
    CAYMANEILANDEN("7092", "Caymaneilanden"),
    CAICOSEILANDEN("7093", "Caicoseilanden"),
    TURKSEILANDEN("7094", "Turkseilanden"),
    BRITS_ANTARCTISCH_TERRITORIUM("7095", "Brits Antarctisch Territorium"),
    BRITS_INDISCHE_OCEAANTERRITORIUM("7096", "Brits Indische Oceaanterritorium"),
    COOKEILANDEN("7097", "Cookeilanden"),
    TOKELAU("7098", "Tokelau"),
    NIEUWCALEDONIE("7099", "Nieuw-Caledonië"),
    HAWAIIEILANDEN("8000", "Hawaii-eilanden"),
    GUAM("8001", "Guam"),
    AMERIKAANSSAMOA("8002", "Amerikaans-Samoa"),
    MIDWAY("8003", "Midway"),
    RIUKIUEILANDEN("8004", "Riukiu-eilanden"),
    WAKE("8005", "Wake"),
    PACIFICEILANDEN("8006", "Pacific-eilanden"),
    GRENADA("8008", "Grenada"),
    MARIANEN("8009", "Marianen"),
    CABINDA("8010", "Cabinda"),
    CANTON_EN_ENDERBURY("8011", "Canton en Enderbury"),
    CHRISTMASEILAND("8012", "Christmaseiland"),
    COCOSEILANDEN("8013", "Cocoseilanden"),
    FAEROER("8014", "Faeröer"),
    MONTSERRAT("8015", "Montserrat"),
    NORFOLK("8016", "Norfolk"),
    BELIZE("8017", "Belize"),
    TASMANIE("8018", "Tasmanië"),
    TURKS_EN_CAICOSEILANDEN("8019", "Turks- en Caicoseilanden"),
    PUERTO_RICO("8020", "Puerto Rico"),
    PAPOEANIEUWGUINEA("8021", "Papoea-Nieuw-Guinea"),
    SALOMONSEILANDEN("8022", "Salomonseilanden"),
    BENIN("8023", "Benin"),
    VIETNAM("8024", "Vietnam"),
    KAAPVERDIE("8025", "Kaapverdië"),
    SEYCHELLEN("8026", "Seychellen"),
    KIRIBATI("8027", "Kiribati"),
    TUVALU("8028", "Tuvalu"),
    SAINT_LUCIA("8029", "Saint Lucia"),
    DOMINICA("8030", "Dominica"),
    ZIMBABWE("8031", "Zimbabwe"),
    DUBAI("8032", "Dubai"),
    NIEUWE_HEBRIDEN("8033", "Nieuwe Hebriden"),
    KANAALEILANDEN("8034", "Kanaaleilanden"),
    MAN("8035", "Man"),
    ANGUILLA("8036", "Anguilla"),
    SAINT_KITTS_EN_NEVIS("8037", "Saint Kitts en Nevis"),
    ANTIGUA("8038", "Antigua"),
    SAINT_VINCENT("8039", "Saint Vincent"),
    GILBERTEILANDEN("8040", "Gilberteilanden"),
    PANAMAKANAALZONE("8041", "Panamakanaalzone"),
    SAINT_KITTS_NEVIS_EN_ANGUILLA("8042", "Saint Kitts, Nevis en Anguilla"),
    BELAU("8043", "Belau"),
    PALAU("8044", "Palau"),
    ANTIGUA_EN_BARBUDA("8045", "Antigua en Barbuda"),
    NEWFOUNDLAND("9000", "Newfoundland"),
    NYASALAND("9001", "Nyasaland"),
    ERITREA("9003", "Eritrea"),
    IFNI("9005", "Ifni"),
    BRITSKAMEROEN("9006", "Brits-Kameroen"),
    KEIZER_WILHELMSLAND("9007", "Keizer Wilhelmsland"),
    CONGO("9008", "Congo"),
    CONGOKINSHASA("9009", "Congo-Kinshasa"),
    MADAGASKAR("9010", "Madagaskar"),
    CONGOBRAZZAVILLE("9013", "Congo-Brazzaville"),
    LEEWARDEILANDEN("9014", "Leewardeilanden"),
    WINDWARDEILANDEN("9015", "Windwardeilanden"),
    FRANS_TERRITORIUM_VOOR_AFARS_EN_ISSAS("9016", "Frans Territorium voor Afars en Issa's"),
    PHOENIXEILANDEN("9017", "Phoenixeilanden"),
    PORTUGEESGUINEE("9020", "Portugees-Guinee"),
    DUITS_ZUIDWESTAFRIKA("9022", "Duits Zuidwest-Afrika"),
    NAMIBIE("9023", "Namibië"),
    BRITSSOMALILAND("9027", "Brits-Somaliland"),
    ITALIAANSSOMALILAND("9028", "Italiaans-Somaliland"),
    NEDERLANDSINDIE("9030", "Nederlands-Indië"),
    BRITSGUYANA("9031", "Brits-Guyana"),
    SWAZILAND("9036", "Swaziland"),
    QATAR("9037", "Qatar"),
    ESWATINI("9038", "Eswatini"),
    ADEN("9041", "Aden"),
    ZUIDARABISCHE_FEDERATIE("9042", "Zuid-Arabische Federatie"),
    EQUATORIAALGUINEA("9043", "Equatoriaal-Guinea"),
    SPAANSGUINEE("9044", "Spaans-Guinee"),
    VERENIGDE_ARABISCHE_REPUBLIEK("9047", "Verenigde Arabische Republiek"),
    BERMUDA("9048", "Bermuda"),
    SOVJETUNIE("9049", "Sovjet-Unie"),
    DUITS_OOSTAFRIKA("9050", "Duits Oost-Afrika"),
    ZANZIBAR("9051", "Zanzibar"),
    CEYLON("9052", "Ceylon"),
    MUSCAT_EN_OMAN("9053", "Muscat en Oman"),
    TRUCIAL_OMAN("9054", "Trucial Oman"),
    INDOCHINA("9055", "Indochina"),
    MARSHALLEILANDEN("9056", "Marshalleilanden"),
    SARAWAK("9057", "Sarawak"),
    BRITSBORNEO("9058", "Brits-Borneo"),
    SABAH("9060", "Sabah"),
    ABU_DHABI("9061", "Abu Dhabi"),
    AJMAN("9062", "Ajman"),
    BASUTOLAND("9063", "Basutoland"),
    BECHUANALAND("9064", "Bechuanaland"),
    FUJAIRAH("9065", "Fujairah"),
    FRANSKAMEROEN("9066", "Frans-Kameroen"),
    JOHORE("9067", "Johore"),
    KOREA("9068", "Korea"),
    LABUAN("9069", "Labuan"),
    UMM_ALQAIWAIN("9070", "Umm Al-Qaiwain"),
    OOSTENRIJKHONGARIJE("9071", "Oostenrijk-Hongarije"),
    PORTUGEES_OOSTAFRIKA("9072", "Portugees Oost-Afrika"),
    PORTUGEES_WESTAFRIKA("9073", "Portugees West-Afrika"),
    SHARJAH("9074", "Sharjah"),
    STRAITS_SETTLEMENTS("9075", "Straits Settlements"),
    ABESSINIE("9076", "Abessinië"),
    FRANS_WESTAFRIKA("9077", "Frans West-Afrika"),
    FRANS_EQUATORIAALAFRIKA("9078", "Frans Equatoriaal-Afrika"),
    URUNDI("9081", "Urundi"),
    RUANDAURUNDI("9082", "Ruanda-Urundi"),
    GOA("9084", "Goa"),
    DANTZIG("9085", "Dantzig"),
    CENTRAALAFRIKAANSE_REPUBLIEK("9086", "Centraal-Afrikaanse Republiek"),
    DJIBOUTI("9087", "Djibouti"),
    TRANSJORDANIE("9088", "Transjordanië"),
    BONDSREPUBLIEK_DUITSLAND("9089", "Bondsrepubliek Duitsland"),
    VANUATU("9090", "Vanuatu"),
    NIUE("9091", "Niue"),
    SPAANS_NOORDAFRIKA("9092", "Spaans Noord-Afrika"),
    WESTELIJKE_SAHARA("9093", "Westelijke Sahara"),
    MICRONESIA("9094", "Micronesia"),
    SVALBARDEILANDEN("9095", "Svalbardeilanden"),
    INTERNATIONAAL_GEBIED("9999", "Internationaal gebied"),
    NULL("", "Null"),
    ;

    override fun toString(): String {
        return "$landcode: $landnaam"
    }
}