mutation {
    createUserDigitaleAdres(digitaleAdresRequest: {
        waarde: "0611111111",
        type: TELEFOONNUMMER,
        omschrijving: "Privè telefoonnummer"
    }) {
        uuid
        waarde
        type
        omschrijving,
        verificatieDatum,
        verificatieNeeded,
        verificatieCodeVerified
    }
}
