mutation {
    createUserDigitaleAdres(digitaleAdresRequest: {waarde: "0611111111", type: TELEFOONNUMMER, omschrijving: "Privè telefoonnummer", isGeverifieerd: true}) {
        uuid
        waarde
        type
        omschrijving,
        verificatieDatum,
        isGeverifieerd
    }
}
