
query {
    getUserDigitaleAdressen(isStandaardAdres: false) {
        uuid
        waarde
        type
        omschrijving
        referentie,
        verificatieDatum,
        verificatieNeeded,
        isStandaardAdres
    }
}
