# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build validation with Gradle

on:
    push:
        branches:
        - "**"
    pull_request:
        branches: [ "development" ]

permissions:
    contents: read

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   name: Gradle CheckLicense
                run: ./gradlew checkLicense

            -   uses: shallwefootball/s3-upload-action@master
                name: Upload S3
                id: S3
                with:
                    aws_key_id: ${{ secrets.AWS_KEY_ID }}
                    aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
                    aws_bucket: ${{ secrets.AWS_LICENSE_BUCKET }}
                    source_dir: 'build/reports/dependency-license'
                    destination_dir: 'licenses/'

            - uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'
            - name: Gradle build
              uses: gradle/gradle-build-action@v3
              with:
                  gradle-version: 8.5
                  arguments: build

