# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build validation with Gradle

on:
    push:
        branches:
        - "**"
    pull_request:
        branches: [ "development" ]

permissions:
    contents: read

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'
            - name: Gradle build
              uses: gradle/gradle-build-action@v3
              with:
                  gradle-version: 8.5
                  arguments: build

            - name: set env
              run: echo "VERSION=$(grep "version" gradle.properties | sed 's/^.*=//')" >> $GITHUB_ENV

            - name: Gradle CheckLicense
              run: ./gradlew checkLicense

            - name: Upload licence report to S3
              run: |
                  mkdir ./build/reports/dependency-license/${VERSION}
                  cp ./build/reports/dependency-license/index.html ./build/reports/dependency-license/${VERSION}/licence-report.html
                  aws s3 cp ./build/reports/dependency-license/${VERSION} s3://nl-portal-licenses/licenses/${VERSION} --recursive
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: 'eu-central-1'

            - name: Gradle htmlDependencyReport
              run: ./gradlew htmlDependencyReport

            - name: Upload dependencies report to S3
              run: |
                  aws s3 cp --recursive build/reports/project/dependencies s3://valtimo-dependency-reports/reports/${VERSION}
                  aws s3 rm --recursive s3://valtimo-dependency-reports/reports/latest
                  aws s3 cp --recursive s3://valtimo-dependency-reports/reports/${VERSION} s3://valtimo-dependency-reports/reports/latest
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: 'eu-central-1'
