name: Publish to github packages and oss

on:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'
            - name: Build with Gradle
              uses: gradle/gradle-build-action@v3
              with:
                  gradle-version: 8.5
                  arguments: build
            -   name: Gradle publish Snapshot to Github
                uses: gradle/gradle-build-action@v3
                with:
                    gradle-version: 8.5
                    arguments: publishDefaultPublicationToGitHubPackagesRepository
                env:
                    USER: ${{ secrets.USER }}
                    TOKEN: ${{ secrets.TOKEN }}

            -   name: Gradle publish Snapshot to OSS
                uses: gradle/gradle-build-action@v3
                with:
                    gradle-version: 8.5
                    arguments: publishDefaultPublicationToSonatypeSnapshotRepository
                env:
                    OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                    OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
                    SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
                    SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
