name: Publish Snapshot
on:
    workflow_call:
        inputs:
            javaVersion:
                description: "The Java Version that should be used in this workflow."
                default: '21'
                type: string
            artifactVersion:
                description: "The Version of the to be published artifact."
                type: string
            targets:
                description: "The target repositories to publish to. See default for options and input format."
                default: "['github-packages', 'sonatype-snapshots']"
                type: string
jobs:
    build-and-publish:
        env:
            JAVA_VERSION: ${{ inputs.javaVersion }}
            ARTIFACT_VERSION: ${{ inputs.artifactVersion }}
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v5
            -   name: Set up JDK ${{ env.JAVA_VERSION }}
                uses: actions/setup-java@v5
                with:
                    java-version: '${{ env.JAVA_VERSION }}'
                    distribution: 'temurin'
            -   name: Set up gradle
                uses: gradle/actions/setup-gradle@v4
            -   name: Gradle publish Snapshot to Github
                if: ${{ contains(fromJSON(inputs.targets),'github-packages') }}
                run: echo 'GitHub Package snapshots have not been migrated over to our new JReleaser-based worfklow. Skipping.'
                env:
                    USER: ${{ secrets.USER }}
                    TOKEN: ${{ secrets.TOKEN }}
            -   name: Gradle deploy snapshot to Sonatype Central (maven-snapshots)
                if: ${{ contains(fromJSON(inputs.targets), 'sonatype-snapshots') }}
                # Must be two separate gradle invocations or it can fail with a race condition.
                # Most likely because JReleaser does not declare a Gradle dependency from `jreleaserdeploy` to `publish`
                run: ./gradlew publish -Pversion=${{env.ARTIFACT_VERSION}} --stacktrace && ./gradlew jreleaserDeploy -Pversion=${{env.ARTIFACT_VERSION}} --stacktrace
                env:
                    JRELEASER_GPG_SECRET_KEY: ${{ secrets.SIGNING_KEY }}
                    JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.SIGNING_KEY_PUBLIC_KEY }}
                    JRELEASER_DEPLOY_MAVEN_NEXUS2_USERNAME: ${{ secrets.SONATYPE_USR }}
                    JRELEASER_DEPLOY_MAVEN_NEXUS2_PASSWORD: ${{ secrets.SONATYPE_PSW }}
                    JRELEASER_GPG_PASSPHRASE: ${{ secrets.SIGNING_KEY_PASSWORD }}
                    JRELEASER_GITHUB_TOKEN: "..." # intentionally an ellipsis
