name: Publish Release
on:
    workflow_call:
        inputs:
            artifactVersion:
                description: "The Version of the to be published artifact."
                type: string
            javaVersion:
                description: "The Java Version that should be used in this workflow."
                default: '21'
                type: string
jobs:
    build-and-publish:
        env:
            ARTIFACT_VERSION: ${{ inputs.artifactVersion }}
            JAVA_VERSION: ${{ inputs.javaVersion }}
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Set up JDK ${{ env.JAVA_VERSION }}
                uses: actions/setup-java@v4
                with:
                    java-version: '${{ env.JAVA_VERSION }}'
                    distribution: 'temurin'
            -   name: Set up gradle
                uses: gradle/actions/setup-gradle@v4
            -   name: Gradle CheckLicense
                run: ./gradlew checkLicense
            -   name: Gradle htmlDependencyReport
                run: ./gradlew htmlDependencyReport
            -   name: Publish to Sonatype Central with Gradle
                # Must be two separate gradle invocations or it can fail with a race condition. 
                # Most likely because JReleaser does not declare a Gradle dependency from `jreleaserdeploy` to `publish`
                run: ./gradlew publish -Pversion=${{env.ARTIFACT_VERSION}} --stacktrace && ./gradlew jreleaserDeploy -Pversion=${{env.ARTIFACT_VERSION}} --stacktrace
                env:
                    JRELEASER_DEPLOY_MAVEN_MAVENCENTRAL_STAGE: 'UPLOAD' # don't wait for confirmation in the web UI
                    JRELEASER_GPG_SECRET_KEY: ${{ secrets.SIGNING_KEY }}
                    JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.SIGNING_KEY_PUBLIC_KEY }}
                    JRELEASER_DEPLOY_MAVEN_MAVENCENTRAL_USERNAME: ${{ secrets.SONATYPE_USR }}
                    JRELEASER_DEPLOY_MAVEN_MAVENCENTRAL_PASSWORD: ${{ secrets.SONATYPE_PSW }}
                    JRELEASER_GPG_PASSPHRASE: ${{ secrets.SIGNING_KEY_PASSWORD }}
                    JRELEASER_GITHUB_TOKEN: "..." # intentionally an ellipsis
            -   name: Upload licence report to S3
                run: |
                    mkdir ./build/reports/dependency-license/${ARTIFACT_VERSION}
                    cp ./build/reports/dependency-license/index.html ./build/reports/dependency-license/${ARTIFACT_VERSION}/index.html
                    aws s3 cp ./build/reports/dependency-license/${ARTIFACT_VERSION} s3://nl-portal-licenses/licenses/${ARTIFACT_VERSION} --recursive
                env:
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    AWS_DEFAULT_REGION: 'eu-central-1'
            -   name: Upload dependencies report to S3
                run: |
                    aws s3 cp --recursive build/reports/project/dependencies s3://nl-portal-dependency-reports/reports/${ARTIFACT_VERSION}
                    aws s3 rm --recursive s3://nl-portal-dependency-reports/reports/latest
                    aws s3 cp --recursive s3://nl-portal-dependency-reports/reports/${ARTIFACT_VERSION} s3://nl-portal-dependency-reports/reports/latest
                env:
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    AWS_DEFAULT_REGION: 'eu-central-1'
            -   name: Summary
                env:
                    VERSION: ${{ inputs.artifactVersion }}
                run: |
                    echo "Successfully staged version ${VERSION}. Confirm its publication manually at: https://central.sonatype.com/publishing"