name: Publish Release
on:
  workflow_call:
    inputs:
      artifactVersion:
        description: "The Version of the to be published artifact."
        type: string
      javaVersion:
        description: "The Java Version that should be used in this workflow."
        default: '21'
        type: string
jobs:
  build-and-publish:
    env:
      ARTIFACT_VERSION: ${{ inputs.artifactVersion }}
      JAVA_VERSION: ${{ inputs.javaVersion }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: '${{ env.JAVA_VERSION }}'
          distribution: 'temurin'
      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew build
      - name: Gradle CheckLicense
        run: ./gradlew checkLicense
      - name: Gradle htmlDependencyReport
        run: ./gradlew htmlDependencyReport
      - name: Publish to Sonatype with Gradle
        run: ./gradlew publishDefaultPublicationToSonatypeRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
      - name: Upload licence report to S3
        run: |
          mkdir ./build/reports/dependency-license/${ARTIFACT_VERSION}
          cp ./build/reports/dependency-license/index.html ./build/reports/dependency-license/${ARTIFACT_VERSION}/index.html
          aws s3 cp ./build/reports/dependency-license/${ARTIFACT_VERSION} s3://nl-portal-licenses/licenses/${ARTIFACT_VERSION} --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-central-1'
      - name: Upload dependencies report to S3
        run: |
          aws s3 cp --recursive build/reports/project/dependencies s3://nl-portal-dependency-reports/reports/${ARTIFACT_VERSION}
          aws s3 rm --recursive s3://nl-portal-dependency-reports/reports/latest
          aws s3 cp --recursive s3://nl-portal-dependency-reports/reports/${ARTIFACT_VERSION} s3://nl-portal-dependency-reports/reports/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-central-1'
