# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build release


on:
    push:
        tags:
            - '*'

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'
            - name: Build with Gradle
              uses: gradle/gradle-build-action@0bfe00a136db5e61ba3416b372542a65863a9fee
              with:
                  arguments: build
            - name: Gradle publish
              uses: gradle/gradle-build-action@v2
              with:
                  gradle-version: 8.4
                  arguments: publish
              env:
                  #USER: ${{ secrets.GITHUB_TOKEN }}
                  #TOKEN: ${{ secrets.GITHUB_ACTOR }}
                  USER: ${{ secrets.USER }}
                  TOKEN: ${{ secrets.TOKEN }}
            - name: Create a Release
              uses: elgohr/Github-Release-Action@20231005120738
              env:
                  GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
              with:
                  title: PortalBackendLibrariesRelease