# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Publish


on:
  push:
    branches:
     - "release/**"
     - "develop"

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'
            - name: Build with Gradle
              uses: gradle/gradle-build-action@v3
              with:
                  gradle-version: 8.5
                  arguments: build
            - name: Gradle publish Release toStaging
              if: startsWith(github.ref_name, 'release/')
              uses: gradle/gradle-build-action@v3
              with:
                  gradle-version: 8.5
                  arguments: publishDefaultPublicationToSonatypeRepository
              env:
                  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                  OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
                  SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
                  SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

            -   name: Gradle publish Snapshot to OSS
                if: github.ref_name == '/refs/head/develop'
                uses: gradle/gradle-build-action@v3
                with:
                    gradle-version: 8.5
                    arguments: publishDefaultPublicationToSonatypeSnapshotRepository
                env:
                    OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
                    OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
                    SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
                    SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
            -   name: Gradle publish Snapshot to Github
                if: github.ref_name == '/refs/head/develop'
                uses: gradle/gradle-build-action@v3
                with:
                    gradle-version: 8.5
                    arguments: publishDefaultPublicationToGitHubPackagesRepository
                env:
                    USER: ${{ secrets.USER }}
                    TOKEN: ${{ secrets.TOKEN }}
            - name: Create a Release
              if: startsWith(github.ref_name, 'release/')
              uses: elgohr/Github-Release-Action@20231116201936
              env:
                  GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
              with:
                  title: PortalBackendLibrariesRelease
